name: Unity Test Runner

on: 
  push:
    branches: [ main ]   # Triggers on push to main branch
  pull_request:
    branches: [ main ]   # Triggers on pull request to main branch

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest  # You can also use macos-latest for mac builds

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: run tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: ./
        githubToken: ${{ secrets.GITHUB_TOKEN }}
